CREATE SCHEMA IF NOT EXISTS conta_cud;
CREATE SCHEMA IF NOT EXISTS conta_r;
CREATE SCHEMA IF NOT EXISTS ms_gerente;
CREATE SCHEMA IF NOT EXISTS ms_cliente;
CREATE SCHEMA IF NOT EXISTS ms_orquestrador;